### ISSUE TITLE
Do we have to set sequenceNumbers?

### ISSUE THREAD

**Issue by gitmachtl** [input-output-hk/offchain-metadata-tools#16]
Short question about sequenceNumbers. Is it ok to swap out the json file with a totally fresh one from scratch with sequenceNumbers=0? Or is it required to increment the sequenceNumbers at all costs to update an entry? 

I updated my SPO scripts to increment the sequenceNumber in the draft json before the signing, that should be ok right?

_Originally posted by @gitmachtl in https://github.com/input-output-hk/offchain-metadata-tools/issues/8#issuecomment-819321857_

**Comment by sevanspowell** [comment]
Great question, I've had to go check myself.

In the current state, a property that was present before, and is present after, must have an incremented sequence number if it was changed - even if it's a completely different value.

To address the other part of your original question: yeah, the token-metadata-creator currently provides no way to increment sequence numbers. You have to make your changes, increment the sequence numbers manually, then re-attest the changes using the token-metadata-creator `-a` flag or similar, in that order, because the attestation attests to the sequence number as well as the value.

**Comment by sevanspowell** [comment]
Please let me know if I haven't answered your question properly. I'm not sure I completely understood.

**Comment by gitmachtl** [comment]
Thx. I think i am good. I track the sequenceNumber in my scripts and everytime someone generates a new <SUBJECT>.json for the registry it autoincrements the sequenceNumber before the signing. So, i think there should be an "How to update" section in the README to point this out that every changed/updated parameter in a later version must have a higher sequenceNumber. 

But, do we really need that sequenceNumber at all? Isn't the token-registry-server just making a 1:1 copy of the Github entries? No matter what you update in them? Will the token-registry-server clear out the metadata if you delete the submitted JSON file?

**Comment by sevanspowell** [comment]
> But, do we really need that sequenceNumber at all?

Sequence numbers are better explained in the [draft CIP](https://github.com/michaelpj/CIPs/blob/cip-metadata-server/cip-metadata-server.md), but to sum it up:

Sequence numbers are required to prevent an attacker from finding a previous entry of yours, and overwriting your existing entry with an old entry.

>  Isn't the token-registry-server just making a 1:1 copy of the Github entries?

Yes, the token-registry-server doesn't care about the sequence number, only the [pull request validation step](https://github.com/cardano-foundation/cardano-token-registry/blob/master/.github/workflows/ci.yaml#L81) cares about the sequence number.

> Will the token-registry-server clear out the metadata if you delete the submitted JSON file?

It doesn't :( It's a flaw in the current design, only additions to the GitHub repo are are reflected in the backend. Removals from the GitHub repo are not reflected in the backend. You've got to remove them from the backend database manually atm.

**Comment by gitmachtl** [comment]
Thx
