### ISSUE TITLE
Building the nix project

### ISSUE THREAD

**Issue by varianchu** [input-output-hk/offchain-metadata-tools#21]
Hi,

so I was trying to build the nix project of the offchain-metadata-tools, however I am unsure if I built it correctly as I am encountering this warning/issue: trace: 

_Using IOHK default nixpkgs
trace: WARNING: 8.10.2 is out of date, consider using 8.10.4.
trace: To make project.plan-nix for offchain-metadata-tools-src a fixed-output derivation but not materialized, set `plan-sha256` to the output of the 'calculateMaterializedSha' script in 'passthru'.
trace: To materialize project.plan-nix for offchain-metadata-tools-src entirely, pass a writable path as the `materialized` argument and run the 'updateMaterialized' script in 'passthru'.
trace: WARNING: 8.10.2 is out of date, consider using 8.10.4.
/nix/store/q0ykp3d93k80j1bhvl356qpbkf9x2lqc-metadata-validator-github-tarball
/nix/store/7vijzx6m0rib076afsalgjfz543m1qid-offchain-metadata-tools-src-plan-to-nix-pkgs
/nix/store/7gxcqnihhyzlgd60pqn3qan0wqvbmidd-project-coverage-report
/nix/store/rwwwg90igc4bi1m2i3vfqv80kfgnla2x-haskell-nix-roots-ghc8102
/nix/store/cc7z5y64209kkwc5m3x8bgfzca9vjyf4-token-metadata-creator_

And when I try to use the command "token-metadata-creator" - command is not found.

**Comment by varianchu** [comment]
hello any ideas how to fix this?

**Comment by sevanspowell** [comment]
Hey @varianchu! Sorry I missed this, I'm going to have to figure out a better notification system for myself.

From the output you've provided, nothing looks wrong.

Instead of executing:
```
$ token-metadata-creator
```

Execute:
```
/nix/store/cc7z5y64209kkwc5m3x8bgfzca9vjyf4-token-metadata-creator/bin/token-metadata-creator
```

There should also be a "result" symlink in the directory you built the project, you can use that instead of the nix/store/ path.

i.e.:
```
lrwxrwxrwx  1 sam users  101 Apr 22 10:25 result -> /nix/store/jqqs9rk4rgwnjq0bi181lf0vskjd2kgr-token-metadata-creator-exe-token-metadata-creator-0.1.0.0
```

I suspect this is the same issue with the test output you sent me. You'll need to set your path to:

```
export PATH="/nix/store/cc7z5y64209kkwc5m3x8bgfzca9vjyf4-token-metadata-creator/bin/:$PATH"
```

to have token-metadata-creator available in your PATH and to run the nodejs tests.

**Comment by varianchu** [comment]
Yes! Thank you! I tried it now and it is working! I am not familiar with
nix so much thats why I encounter this problems.

I was able to submit a pull request in the testnet. I am unsure if i did it
correctly.

https://github.com/input-output-hk/metadata-registry-testnet/pull/101

Thank you so much for your help. I am very excited to create my new coin in
the mainnet in the near future

**Comment by sevanspowell** [comment]
Looks good to me!

The automated check passed too! https://github.com/input-output-hk/metadata-registry-testnet/runs/2464008705

I'll merge it :+1:

**Comment by varianchu** [comment]
Hi samuel! That is awesome! Where can i check this? Can i also see it in
pool.pm?

**Comment by sevanspowell** [comment]
You can query the testnet metadata-server using this URL: https://metadata.cardano-testnet.iohkdev.io/metadata/8212656e585a28628bd2f2a5b1b6eaa2903d7b86ecbaea5ba64129915643434f494e

For mainnet, the URL is: https://metadata.cardano-testnet.iohkdev.io/metadata/<subject>, but only after you merge your metadata to `cardano-foundation/cardano-token-registry`.

On mainnet, you should be able to view your metadata in Daedalus. If you look at the transaction where you minted the tokens.

**Comment by sevanspowell** [comment]
I'm not super sure about external tools like pool.pm.

**Comment by varianchu** [comment]
Alright! Thank you so much for your help. I will check on this

**Comment by varianchu** [comment]
Just in case if I plan to update the metadata, I would just need to repeat
the process and request for another pull, correct?

**Comment by sevanspowell** [comment]
Yep, just repeat the process :+1:

**Comment by varianchu** [comment]
Alright thank you!

**Comment by varianchu** [comment]
Hi Samuel,

Sorry to bother you once again. Do you also handle the merging for the
mainnet token registry? How long does it usually take to approve a pull
request?

Thanks!

Varian

**Comment by sevanspowell** [comment]
I don't handle merging for the [mainnet token registry](https://github.com/cardano-foundation/cardano-token-registry), the cardano-foundation organization does, but from what I've observed it usually takes a few days. Sometimes less, but it depends. Because it's managed by humans the time to merge can vary based on workload.

**Comment by varianchu** [comment]
Alright! Thanks so much samuel! I was able to create the token already. It
took around a day.

https://pool.pm/c5b4292dbeccfa45a5444396dcfcbfff12ebece843fd9695a8b6f1ae.FirstKokoLoko

**Comment by sevanspowell** [comment]
Nice! :+1:
