### ISSUE TITLE
setup CI check - sequence numbers incremental only + required if changing 

### ISSUE THREAD

**Issue by crptmppt** [input-output-hk/offchain-metadata-tools#3]
setup CI check - sequence numbers incremental only + required if changing

**Comment by sevanspowell** [comment]
Done! Example [PR](https://github.com/input-output-hk/metadata-registry-testnet/pull/92) and [failed check](https://github.com/input-output-hk/metadata-registry-testnet/pull/92/checks?check_run_id=2348605270).
