### ISSUE TITLE
token-metadata-creator: command not found

### ISSUE THREAD

**Issue by anhdungle93** [input-output-hk/offchain-metadata-tools#32]
I tried to build the project using these steps 
```
Using Nix

From the root directory of the project nix-build -A project will build all project components, including test suites.

To build a particular executable, say token-metadata-creator, use nix-build -A token-metadata-creator.

To enter a development shell, use nix-shell default.nix -A shell. This will enter a development shell for which haskell.nix provides all dependencies.

```
but then I still couldn't use the token-metadata-creator (neither in nix-shell nor outside it).

**Comment by sevanspowell** [comment]
After running `nix-build -A token-metadata-creator`, a symlink should appear in your current directory called "token-metadata-creator". You should be able to run it with `./token-metadata-creator/bin/token-metadata-creator`.

That's a bit of a nix-specific stumbling block, `nix-build` doesn't add the software to your PATH.

If that doesn't work would you please tell me what part of the instructions is failing? Is it the build step (`nix-build`)?
