### ISSUE TITLE
token-metadata-creator won't execute

### ISSUE THREAD

**Issue by BisonBucks** [input-output-hk/offchain-metadata-tools#47]
I'm very new to linux, so maybe i'm just doing something wrong on my end, but I'm running Ubuntu through wsl.  I've cloned the offchain-metadata-tools and run nix-build -A project.  where I run into problems is when I try to execute token-metadata-creator I get this : 

[nix-shell:~/offchain-metadata-tools]$ token-metadata-creator
bash: token-metadata-creator: command not found

**Comment by BisonBucks** [comment]
Here is everything i did, if that is helphful

bisonbucks@DESKTOP-7UH3K14:~$ git clone https://github.com/input-output-hk/offchain-metadata-tools.git
Cloning into 'offchain-metadata-tools'...
remote: Enumerating objects: 2177, done.
remote: Counting objects: 100% (561/561), done.
remote: Compressing objects: 100% (333/333), done.
remote: Total 2177 (delta 271), reused 403 (delta 191), pack-reused 1616
Receiving objects: 100% (2177/2177), 1.75 MiB | 4.02 MiB/s, done.
Resolving deltas: 100% (901/901), done.
bisonbucks@DESKTOP-7UH3K14:~$ ls
cardano-src  install-nix.sh  offchain-metadata-tools  tmp

bisonbucks@DESKTOP-7UH3K14:~$ cd offchain-metadata-tools/
bisonbucks@DESKTOP-7UH3K14:~/offchain-metadata-tools$ nix-build -A project
trace: Using IOHK default nixpkgs
trace: WARNING: 8.10.2 is out of date, consider using 8.10.4.
trace: To make project.plan-nix for offchain-metadata-tools-src a fixed-output derivation but not materialized, set `plan-sha256` to the output of the 'calculateMaterializedSha' script in 'passthru'.
trace: To materialize project.plan-nix for offchain-metadata-tools-src entirely, pass a writable path as the `materialized` argument and run the 'updateMaterialized' script in 'passthru'.
building '/nix/store/n956vxpp9kfj259czghgf8dgly4p3gp0-git-ls-files.drv'...
trace: WARNING: 8.10.2 is out of date, consider using 8.10.4.
/nix/store/vh0zf2rxck5vf7fl1driwhyh0zwy9xdx-metadata-validator-github-tarball
/nix/store/51a2a0y625ivrwbvkpqil8ybyhbyd7pm-offchain-metadata-tools-src-plan-to-nix-pkgs
/nix/store/y1m1p708ncyfca4kjf1b1yqhvczshh2f-project-coverage-report
/nix/store/g5z6m1wjnpa8fy82hdgpm9w3i81as1z4-haskell-nix-roots-ghc8102
/nix/store/2ynbbg6wpl4vbm9j6p3q1b20wyqvrxg4-token-metadata-creator

bisonbucks@DESKTOP-7UH3K14:~/offchain-metadata-tools$ ls
CHANGELOG.md  README.md  cabal-nix.project  default.nix   metadata-server          metadata-validator-github  nix          result-2  result-5   test
LICENSE       Setup.hs   cabal.project      docs          metadata-store-postgres  metadata-webhook           release.nix  result-3  scripts    token-metadata-creator
Makefile      bors.toml  ci                 metadata-lib  metadata-sync            mkdocs.yml                 result       result-4  shell.nix
bisonbucks@DESKTOP-7UH3K14:~/offchain-metadata-tools$ token-metadata-creator
token-metadata-creator: command not found

bisonbucks@DESKTOP-7UH3K14:~/offchain-metadata-tools$ nix-shell default.nix -A shell
trace: Using IOHK default nixpkgs
trace: WARNING: 8.10.2 is out of date, consider using 8.10.4.
trace: To make project.plan-nix for offchain-metadata-tools-src a fixed-output derivation but not materialized, set `plan-sha256` to the output of the 'calculateMaterializedSha' script in 'passthru'.
trace: To materialize project.plan-nix for offchain-metadata-tools-src entirely, pass a writable path as the `materialized` argument and run the 'updateMaterialized' script in 'passthru'.
trace: WARNING: 8.10.2 is out of date, consider using 8.10.4.
trace: To make project.plan-nix for hoogle a fixed-output derivation but not materialized, set `plan-sha256` to the output of the 'calculateMaterializedSha' script in 'passthru'.
trace: To materialize project.plan-nix for hoogle entirely, pass a writable path as the `materialized` argument and run the 'updateMaterialized' script in 'passthru'.
trace: No index state specified for cabal-install, using the latest index state that we know about (2021-03-17T00:00:00Z)!

[nix-shell:~/offchain-metadata-tools]$ token-metadata-creator
bash: token-metadata-creator: command not found

[nix-shell:~/offchain-metadata-tools]$ /nix/store/2ynbbg6wpl4vbm9j6p3q1b20wyqvrxg4-token-metadata-creator
bash: /nix/store/2ynbbg6wpl4vbm9j6p3q1b20wyqvrxg4-token-metadata-creator: Is a directory

**Comment by sevanspowell** [comment]
Hi @BisonBucks,

This is a bit of a documentation issue, sorry about that!

When you run `nix-build -A project`, it does build all the project, but it doesn't add any project executables to your $PATH. Hence why you can't just execute `token-metadata-creator`.

To build just the token-metadata-creator executable, use `nix-build -A token-metadata-creator`.

The result will be placed in `./result/bin/token-metadata-creator`.

You can then add this `bin` directory to your $PATH if you wish.

**Comment by BisonBucks** [comment]
Thank you! that worked.  I really appreciate your help

**Comment by sevanspowell** [comment]
No worries at all, thanks for your patience :)
